version: "3.9"

services:

  #redis:
  #  extends:
  #    file: docker-compose.common.yml
  #    service: redis

  postgresql:
    extends:
      file: docker-compose.common.yml
      service: postgresql
      
  #rabbitmq:
  #  extends:
  #    file: docker-compose.common.yml
  #    service: rabbitmq
