# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Setup permissions
      run: sudo mkdir -p /usr/share/ && sudo chown $USER:$USER /usr/share/
    - name: Setup restore permissions
      run: sudo chown -R $USER:$USER /home/gitrunner/SemiTrailer
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Show
      run: pwd
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Start
      run: ls; docker-compose -f docker-compose.api.yml stop && docker-compose -f docker-compose.api.yml rm -f && docker-compose -f docker-compose.api.yml up --build -d